// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import { defineConfig } from "prisma/config"

const isProd = process.env.NODE_ENV === "production"

export default defineConfig({
  schema: "./schema.prisma",
  datasource: {
    url: isProd
      ? process.env.TURSO_DATABASE_URL
      : "file:../dev.db",
  },
})
